# Generated by Django 5.0.6 on 2024-06-11 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address1',
            new_name='Sh_address1',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address2',
            new_name='Sh_address2',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='city',
            new_name='Sh_city',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='country',
            new_name='Sh_country',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='email',
            new_name='Sh_email',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='fullName',
            new_name='Sh_fullName',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='state',
            new_name='Sh_state',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='user',
            new_name='Sh_user',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zipCode',
            new_name='Sh_zipCode',
        ),
    ]
