# Generated by Django 5.0.6 on 2024-06-11 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_address1_shippingaddress_sh_address1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='Sh_user',
            new_name='user',
        ),
    ]
