# Generated by Django 5.0.6 on 2024-06-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_rename_sh_user_shippingaddress_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='Sh_address2',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
