# Generated by Django 5.0.6 on 2024-06-04 16:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CatName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProdName', models.CharField(max_length=50)),
                ('ProdPrice', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('ProdDesc', models.CharField(max_length=500)),
                ('ProdImage', models.ImageField(upload_to='uploads/product/')),
                ('ProdCat', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderQuant', models.IntegerField(default=1)),
                ('OrderAddress', models.CharField(max_length=200)),
                ('OrderPhone', models.CharField(max_length=20)),
                ('OrderTime', models.DateTimeField(default=datetime.datetime.now)),
                ('OrderStatus', models.BooleanField(default=False)),
                ('OrderUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
                ('OrderProd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
